Repository ministryofjustice/serve-opg, pull requests merged in 2022-11, with the labels that each got.

#533 SER-183 - increase threshold of response time alarm
  terraform/alarms.tf
  terraform/cloudwatch.tf
  terraform/notifications.tf
Labels: infrastructure

#534 SER-185 - use updated sirius production url
  terraform/terraform.tfvars.json
Labels: infrastructure

#537 SER-181 - upgrade rds instance class
  terraform/rds.tf
Labels: infrastructure

#536 SER-181 - rollout postgres 13 to dev
  serve-api/internal/db/Dockerfile
  terraform/locals.tf
  terraform/rds.tf
  terraform/terraform.tfvars.json
Labels: infrastructure, api

#538 Try encore update to 2.0
  .github/workflows/containers.yml
  .github/workflows/web.yml
  serve-web/package.json
  serve-web/yarn.lock
Labels: pipeline, web

#539 SER-181 - rollout postgres 13 prod
  terraform/rds.tf
  terraform/terraform.tfvars.json
Labels: infrastructure
