Repository ministryofjustice/serve-opg, pull requests merged in 2022-12, with the labels that each got.

#542 SER-181 - update prod rds instance class before version update
  terraform/terraform.tfvars.json
Labels: infrastructure

#543 SER-181 - re-apply rds prod version
  terraform/terraform.tfvars.json
Labels: infrastructure

#529 SER-171 - add php package caching to behat job
  .github/workflows/behat.yml
  .github/workflows/web.yml
Labels: pipeline

#541 SER-191 - append envrionment name to alarm names
  terraform/alarms.tf
Labels: infrastructure

#535 SER-186 - resolve some Actions deprecation warnings
  .github/workflows/api.yml
  .github/workflows/behat.yml
  .github/workflows/containers.yml
  .github/workflows/deploy.yml
  .github/workflows/scanner.yml
  .github/workflows/tags.yml
  .github/workflows/web.yml
Labels: pipeline

#549 Remove obsolete scanner workflow
  .github/workflows/scanner.yml
Labels: pipeline

#548 Bump decode-uri-component from 0.2.0 to 0.2.2 in /serve-web
  serve-web/yarn.lock
Labels: web
