Repository ministryofjustice/serve-opg, pull requests merged in 2023-03, with the labels that each got.

#557 Upgrade to TF 1.2.3
  terraform/.terraform.lock.hcl
  terraform/versions.tf
Labels: infrastructure

#546 Move US-east alert to serve channel
  terraform/notifications.tf
Labels: infrastructure

#559 SER-204 - Upgrade to latest version of aws notify slack #patch
  .github/workflows/deploy.yml
  terraform/.terraform.lock.hcl
  terraform/notifications.tf
Labels: pipeline, infrastructure

#560 Add a prefix for us east iam role #patch
  terraform/notifications.tf
Labels: infrastructure

#562 Exclude dependabot PRs from trying to push containers
  .github/workflows/containers.yml
Labels: pipeline
